workflows:
  unity-ios-build:
    name: Unity 6 iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - unity
      vars:
        UNITY_VERSION: "6000.2.6f2" 
    scripts:
      - name: Setup Build Tools
        script: |
          # This installs the missing unity-installer tool
          pip install codemagic-cli-tools
      - name: Install Unity 6
        script: |
          echo "Downloading Unity $UNITY_VERSION and iOS Support..."
          # Now that we installed the tool, we run it
          unity-installer --version $UNITY_VERSION --platform ios
      - name: Locate Unity
        script: |
          # The installer puts it in a specific folder. Let's find it.
          UNITY_BIN="/Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity"
          echo "export UNITY_BIN=\"$UNITY_BIN\"" >> $CM_ENV
          echo "Unity located at: $UNITY_BIN"
      - name: Create Editor Folder
        script: mkdir -p Assets/Editor
      - name: Create Build Script
        script: |
          cat <<EOF > Assets/Editor/BuildScript.cs
          using UnityEditor;
          public class BuildScript {
              public static void BuildIOS() {
                  BuildPlayerOptions options = new BuildPlayerOptions();
                  // VERIFY: Make sure your scene is named SampleScene.unity
                  options.scenes = new[] { "Assets/Scenes/SampleScene.unity" }; 
                  options.locationPathName = "build/ios";
                  options.target = BuildTarget.iOS;
                  options.options = BuildOptions.None;
                  BuildPipeline.BuildPlayer(options);
              }
          }
          EOF
      - name: Build Xcode Project
        script: |
          $UNITY_BIN \
            -batchmode \
            -quit \
            -projectPath . \
            -executeMethod BuildScript.BuildIOS \
            -buildTarget iOS \
            -logFile /dev/stdout
      - name: Build Unsigned App
        script: |
          cd build/ios
          xcodebuild -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            AD_HOC_CODE_SIGNING_ALLOWED=YES \
            build
    artifacts:
      - build/ios/build/Release-iphoneos/*.app