workflows:
  unity-ios-build:
    name: Unity 6 iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - unity
      vars:
        UNITY_VERSION: "6000.2.6f2" 
    scripts:
      - name: Install Unity Engine
        script: |
          # 1. Install the tool
          pip install codemagic-cli-tools
          
          # 2. HUNT DOWN the tool (Stop guessing the path)
          echo "Searching for unity-installer executable..."
          INSTALLER=$(find /Users/builder -name "unity-installer" -type f -perm +111 | head -n 1)
          
          if [ -z "$INSTALLER" ]; then
            echo "Installer not found! listing pip folders for debug:"
            pip show codemagic-cli-tools
            exit 1
          fi

          echo "Found installer at: $INSTALLER"
          
          # 3. Run it using the specific path found
          echo "Downloading Unity $UNITY_VERSION... this will take several minutes."
          $INSTALLER --version $UNITY_VERSION --platform ios
      - name: Locate Unity
        script: |
          # Finds the newly installed Unity 6 binary
          UNITY_BIN=$(find /Applications/Unity/Hub/Editor -name "Unity" -type f -path "*/Contents/MacOS/Unity" | head -n 1)
          if [ -z "$UNITY_BIN" ]; then
            echo "Unity not found after install!"
            exit 1
          fi
          echo "export UNITY_BIN=\"$UNITY_BIN\"" >> $CM_ENV
          echo "Unity located at: $UNITY_BIN"
      - name: Create Editor Folder and Build Script
        script: |
          mkdir -p Assets/Editor
          cat <<EOF > Assets/Editor/BuildScript.cs
          using UnityEditor;
          public class BuildScript {
              public static void BuildIOS() {
                  BuildPlayerOptions options = new BuildPlayerOptions();
                  options.scenes = new[] { "Assets/Scenes/SampleScene.unity" }; 
                  options.locationPathName = "build/ios";
                  options.target = BuildTarget.iOS;
                  options.options = BuildOptions.None;
                  BuildPipeline.BuildPlayer(options);
              }
          }
          EOF
      - name: Build Xcode Project
        script: |
          $UNITY_BIN \
            -batchmode \
            -quit \
            -projectPath . \
            -executeMethod BuildScript.BuildIOS \
            -buildTarget iOS \
            -logFile /dev/stdout
      - name: Build Unsigned App
        script: |
          cd build/ios
          xcodebuild -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            AD_HOC_CODE_SIGN_IDENTITY=YES \
            build
    artifacts:
      - build/ios/build/Release-iphoneos/*.app